settings:
  docker:
    parent_image: 992382797823.dkr.ecr.eu-central-1.amazonaws.com/zenml-rlwlcs:latest
    skip_build: True
  orchestrator.sagemaker:
    synchronous: false
    
parameters:
  user_full_name: Nik # [First Name(s)] [Last Name]
  links:
    # Personal Blog
    - https://limcheekin.blogspot.com/2021/09/beyond-solidity-language.html
    - https://limcheekin.blogspot.com/2021/07/closing-gap.html
    - https://limcheekin.blogspot.com/2021/03/flutter-widgets-explorer-go-live.html
    - https://limcheekin.blogspot.com/2020/12/integrating-multiple-data-sources-to.html
    - https://limcheekin.blogspot.com/2020/12/implementing-graphql-api-with-micronaut.html
    - https://limcheekin.blogspot.com/2020/12/standard-query-language-for-your-web.html
    - https://limcheekin.blogspot.com/2020/11/resurgence.html
    - https://limcheekin.blogspot.com/2013/03/web-development-in-firefox-using.html
    - https://limcheekin.blogspot.com/2013/02/jquery-validation-ui-plugin-141.html
    - https://limcheekin.blogspot.com/2012/08/simplifying-jquery-grid-jqgrid-and.html
    - https://limcheekin.blogspot.com/2012/08/twitter-bootstrap-multiple-columns-form.html
    - https://limcheekin.blogspot.com/2012/07/simplifying-grails-flexigrid-integration.html
    - https://limcheekin.blogspot.com/2012/07/grails-activiti-evolution.html
    - https://limcheekin.blogspot.com/2012/06/my-blog-hits-50k-pageviews.html
    - https://limcheekin.blogspot.com/2012/05/application-skeleton-of-vaadin-spring.html
    - https://limcheekin.blogspot.com/2012/04/grails-adoption-in-malaysia.html
    - https://limcheekin.blogspot.com/2011/07/my-first-experience-of-outsourcing.html
    - https://limcheekin.blogspot.com/2011/04/open-letter-to-early-access-registered.html
    - https://limcheekin.blogspot.com/2011/03/resurrection-of-malaysia-groovy-and.html
    - https://limcheekin.blogspot.com/2011/03/action-notes-of-how-to-make-money-in-6.html
    - https://limcheekin.blogspot.com/2011/03/looking-for-developers-working-on-open.html
    - https://limcheekin.blogspot.com/2011/02/crossing-chasm-in-me.html
    - https://limcheekin.blogspot.com/2011/02/typography-should-jquery-form-builder.html
    - https://limcheekin.blogspot.com/2011/01/freemarker-vs-gsp-for-dynamic-template_27.html
    - https://limcheekin.blogspot.com/2011/01/request-for-comment-jquery-form-builder.html
    - https://limcheekin.blogspot.com/2011/01/freemarker-vs-gsp-for-dynamic-template.html
    - https://limcheekin.blogspot.com/2011/01/kick-off-jquery-form-builder-plugin.html
    - https://limcheekin.blogspot.com/2011/01/jquery-form-builder-plugin-project-01.html
    - https://limcheekin.blogspot.com/2009/07/behavior-driven-development-generating.html
    # Medium
    - https://medium.com/@limcheekin/unleashing-the-power-of-open-source-text-embeddings-with-open-text-embeddings-e8fc684aa2cd
    - https://medium.com/@limcheekin/kickstart-your-dapps-development-with-the-ethereum-dapps-next-js-boiletplate-fdc4d1af22c6
    - https://medium.com/@limcheekin/flutter-file-upload-ced5b35ec4c0
    - https://medium.com/@limcheekin/nft-erc721-with-physical-asset-delivery-and-secondary-royalties-erc2981-f63ce60ed4e0
    - https://medium.com/@limcheekin/erc20-token-sales-with-whitelisting-feature-9b1ea76cbbb4
    - https://medium.com/@limcheekin/solidity-and-truffle-continuous-integration-setup-with-github-actions-221149eabcca
    - https://medium.com/@limcheekin/flutter-app-architecture-flutter-bloc-or-flutter-clean-architecture-f0c154edce7d
    - https://medium.com/@limcheekin/free-code-audit-for-flutter-project-33735cbd649c
    - https://medium.com/@limcheekin/pay-0-01-for-cloud-hosted-mlflow-9b4f96a582e7
    - https://medium.com/@limcheekin/four-key-stages-of-the-machine-learning-process-b0f26ac87f81
    - https://medium.com/@limcheekin/showcase-your-widget-with-flutter-widgets-explorer-a65453c9c4f4
    - https://medium.com/@limcheekin/flutter-navigation-flutter-modular-or-stacked-9fdf39412703
    - https://medium.com/@limcheekin/deploy-serverless-machine-learning-models-to-aws-lambda-8b0cc222d49a
    - https://medium.com/@limcheekin/flutter-multi-modules-support-57e9acd21c7a
    - https://medium.com/@limcheekin/your-first-flutter-app-the-flutter-widgets-explorer-ec35d06568a6
    - https://medium.com/@limcheekin/flutter-widgets-explorer-now-fluwix-8d4c87bf4a3e
